# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tableView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tableView

  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'tableViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tableViewUITests' do
    # Pods for testing
  end

end
